// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "a6d5edd1-cefb-48c7-8db0-c5373997be89");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.auto", false);
user_pref("browser.bookmarks.addedImportButton", false);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.memory.capacity", 0);
user_pref("browser.cache.memory.enable", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.autohideButton", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1642736831);
user_pref("browser.laterrun.bookkeeping.sessionCount", 27);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 116);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons", false);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{9f58b2a3-1943-4317-a175-31739a787f8b}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.activity-stream.section.highlights.includeBookmarks", false);
user_pref("browser.newtabpage.activity-stream.showSearch", false);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.search.update", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20220105212146");
user_pref("browser.shell.checkDefaultBrowser", true);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.buildID", "20220105212146");
user_pref("browser.startup.homepage_override.mstone", "91.5.0");
user_pref("browser.startup.page", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"urlbar-container\",\"home-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":3}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.suggest.engines", false);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("browser.urlbar.suggest.topsites", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("devtools.toolbox.footer.height", 0);
user_pref("devtools.toolbox.force-chrome-prefs", false);
user_pref("devtools.toolbox.sideEnabled", false);
user_pref("devtools.toolbox.sidebar.width", 0);
user_pref("devtools.toolbox.splitconsoleHeight", 0);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "91.5.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "9f57e25f67b64f5ca31e0d5366c9a6de");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.enabled", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220105212146");
user_pref("extensions.lastAppVersion", "91.5.0");
user_pref("extensions.lastPlatformVersion", "91.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.pocket.api", "");
user_pref("extensions.pocket.enabled", false);
user_pref("extensions.pocket.site", "");
user_pref("extensions.screenshots.disabled", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"f4b97daf-c0b3-4929-88da-717c7fac91bd\",\"formautofill@mozilla.org\":\"0aa54141-eb2b-4a5c-aa5e-308dfa221e0d\",\"pictureinpicture@mozilla.org\":\"a4d7620f-b868-448e-b6b6-739f10c18824\",\"proxy-failover@mozilla.com\":\"3fd63288-f6a1-4b47-a6bd-3e23979f102b\",\"screenshots@mozilla.org\":\"a268d616-acee-4c7f-a601-f23830f59ed3\",\"webcompat-reporter@mozilla.org\":\"df25aacc-5872-42c7-8af6-a3aeb9e4d446\",\"webcompat@mozilla.org\":\"67f11f1d-deb8-45ee-9dab-93e71d2c7efe\",\"default-theme@mozilla.org\":\"629e28fd-0a9d-456f-968a-8a0617030599\",\"google@search.mozilla.org\":\"093b6de2-3224-4601-89d3-a3815a5f6770\",\"wikipedia@search.mozilla.org\":\"c855da6d-1eac-4b6a-a65f-67ea935536eb\",\"yahoo-jp-auctions@search.mozilla.org\":\"841f55cf-4e90-4721-8759-af76c227ab0a\",\"bing@search.mozilla.org\":\"929e35bb-4773-42e5-9725-51c4f1da3178\",\"rakuten@search.mozilla.org\":\"8dffd0fb-0758-4ab5-9888-024aec4d6f8b\",\"yahoo-jp@search.mozilla.org\":\"d8a6789a-7faf-47fa-bc99-172a3aa4c41f\",\"ddg@search.mozilla.org\":\"2bc81914-bdf5-45da-b7a6-7bd1a3b8a509\",\"oshiete-goo@search.mozilla.org\":\"951b9f99-eb1f-493f-a6a8-1969257a6e54\",\"amazon@search.mozilla.org\":\"1751c99e-c952-4903-a3e9-1b534b6c43c3\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("print.always_print_silent", true);
user_pref("print.show_print_progress", false);
user_pref("privacy.sanitize.pending", "[]");
user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons", false);
user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features", false);
user_pref("services.sync.prefs.sync.browser.urlbar.suggest.bookmark", false);
user_pref("services.sync.prefs.sync.browser.urlbar.suggest.engines", false);
user_pref("services.sync.prefs.sync.browser.urlbar.suggest.history", false);
user_pref("services.sync.prefs.sync.browser.urlbar.suggest.openpage", false);
user_pref("services.sync.prefs.sync.browser.urlbar.suggest.searches", false);
user_pref("services.sync.prefs.sync.browser.urlbar.suggest.topsites", false);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1642848750);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.pioneer-new-studies-available", true);
user_pref("toolkit.telemetry.previousBuildID", "20220105212146");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.key.menuAccessKeyFocuses", false);
user_pref("xpinstall.whitelist.required", false);
